### ISSUE TITLE
Pulse location every 15 minutes

### ISSUE THREAD

**Issue by bajere** [kvarkson/PhoneGap-iOS-Background-Location-Tracking-Plugin#3]
Hi,

Great plugin, but only the problem i have is that i cant seem to turn the location off and on in at set intervals. Say 15 minutes. is this possible? It just tracks for 14 minutes then ends. (to keep battery life i'm guessing).

**Comment by kvarkson** [comment]
Hi @bajere,

iOS allows us to run background locations services with a few rules. If you just closed the app your location would be updated almost every second. But after 10-15 seconds working in background operations system reduces that frequency and eventually stops. But the locations will be updated if you move from your current place (and this would be most accurate if you went out and use actual GPS and not your wifi or cellular network for tracking). I tested the app when I moved around the city for 3 hours and updates were coming each 10-20 meters.
And as you said this behavior dictated by saving battery policy.

Please try the real location updates and tell me how it worked for you.

**Comment by bajere** [comment]
Hi @kvarkson ,

Thanks for the reply, i will try this today, and take the app out for a few hours and see what happens. I will try and save the lat long to memory so i can read it later as i do not have my database set up online yet. I'll report back here with the info.

Thanks

**Comment by bajere** [comment]
Hi @kvarkson , I think this is working now i have taken the app out for a few hours. Thank you for explaining it all!! :)

**Comment by kvarkson** [comment]
@bajere you are welcome :)
