### ISSUE TITLE
Terminating app due to uncaught exception NSInvalidArgumentException

### ISSUE THREAD

**Issue by NaxYo** [kvarkson/PhoneGap-iOS-Background-Location-Tracking-Plugin#4]
Hi, I'm trying to use the plugin on phonegap 3.1 and in fact it run quite well on iOS 7, but I'm getting this error on iOS 5.1:

Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[CLLocationManager setActivityType:]: unrecognized selector sent to instance ...'

Got no clue about what's going on (I'm not a objective-c guy) so, if any one know something...

**Comment by kvarkson** [comment]
Hi, thanks for the report.

The issues is fixed.
