### ISSUE TITLE
Background continuous reporting

### ISSUE THREAD

**Issue by akshayakrsh** [kvarkson/PhoneGap-iOS-Background-Location-Tracking-Plugin#6]
Hi @kvarkson ,

I am trying to achieve the background reporting in my Phonegap 3.2.0. I'm facing the following issues, just want to know if this plugin handles them:
1. When the app is in background after a while the background reporting stops.
2. To solve problem1, I used the plugin https://github.com/akshayakrsh/com.cleartag.plugins.EnableBackgroundLocation (see that I have set "pausesLocationUpdatesAutomatically" to NO), and the thing started to work pretty nicely. But still I saw 2 issues - 
    a. If the phone is stationary for 4-5 hours at the same location and then starts moving again, the location reporting didnt work.
    b. If the GPS signal was lost in between (while the user was in a tunnel or underground/metro, etc., lets say)...the reporting stopped - I think this is because of the cordova's geolocation plugin.
    c. The battery drained more that usual - not confirmed yet.

So, my question here is...is this plugin addressing all these issues? I need to know this asap for a production release...this is the only thing holding it back!

Thanks a ton!

**Comment by Edward-Price** [comment]
Hi @akshayakrsh i was wondering did you get any feedback or result for your questions. 
I am also looking to have an app continually track location even if the app is in the background or the phone is locked. I ran into the same problems of inactivity disrupting the location reporting as well signal loss.

Have you found out if this plugin gets round these problems?

Thanks :)

**Comment by akshayakrsh** [comment]
Hi @Edward-Price check this plugin https://github.com/christocracy/cordova-plugin-background-geolocation. I just got it added...the developer is quite active and I think the solution is quite good overall.

**Comment by Edward-Price** [comment]
Thanks @akshayakrsh for the quick reply. ill give it a shot and see how it goes.

**Comment by Edward-Price** [comment]
@akshayakrsh I know this isnt the place to be talking about another repo and im sure these comments will get deleted. But do you know of any limitations to the plugin you have directed me towards? or have you come across anything while using it?

**Comment by akshayakrsh** [comment]
@Edward-Price You are right this is not the right place. And before I say anything, I didnt really try the code here to check if its working or not. I preferred to use a plugin instead of raw files (which is not the case) and I was too lazy to convert it to a plugin myself. So may be this code actually does what it says.

As for the other plugin, we are still doing trials with it and it would be too soon to comment about it.

**Comment by kvarkson** [comment]
Hi guys.

Thank you for the question. You have a nice chat here :)

I didn't update the plugin for a long time now, last PhoneGap version that I checked it with was 3.0. It worked very good. As for @akshayakrsh first question - I already answered a similar one here: https://github.com/kvarkson/PhoneGap-iOS-Background-Location-Tracking-Plugin/issues/3. 

Please let me know after testing if you do have any issues with the plugin.

Thanks!
